config/routes.rb
BarviewRor::Application.routes.draw do
  post "fb_update/create"

  get "facebook/create"
  get "facebook/callback"
  delete "facebook/destroy"

  get "forgot_password/index"

  post "forgot_password/create"

  get "viewers/index"

  get "user_questionnaire/index"

  post "user_questionnaire/create"

  get "nearby_bars/index"

  get "about/index"

  get "mobile_info/index"

  get "search/index"

  controller :user_home do
    get 'userhome' => :index
  end

  resources :favorites

  resources :users

  resources :bar_events
  
  controller :admins do
    get 'adminlogin' => :new
    post 'adminlogin' => :create
    delete 'adminlogout' => :destroy
  end
  
  controller :user_login do
    get 'userlogin' => :new
    post 'userlogin' => :create
    delete 'userlogout' => :destroy
  end

  controller :barlogin do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :barhome do
    get 'barhome' => :index
  end

  resources :bars, :barimage

  get "home/index"

  root :to => 'user_home#index', :as => 'userhome'

end

app/models/bar_event.rb
class BarEvent < ActiveRecord::Base
  attr_accessible :bar_id, :detail
  belongs_to :bar
  
  class << self
    def get_events_for_favorites(id)
      return BarEvent.find(:all, :select => "bars.name as name, bar_events.detail as detail", :joins => [:bar], :conditions => ["bars.id in (select f.bar_id from favorites f inner join users u on f.user_id = u.id where u.id = ?)", id])
    end
    
    def get_xml_for_favorites(id)
      xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><events>"
      events = BarEvent.find(:all, :select => "bars.name as name, bar_events.detail as detail", :joins => [:bar], :conditions => ["bars.id in (select f.bar_id from favorites f inner join users u on f.user_id = u.id where u.id = ?)", id])
      for e in events do
        xml += "<event><bar>#{ e.name }</bar><detail>#{ e.detail }</detail></event>"
      end
      
      xml += "</events>"
      
      xml
    end
  end
end

app/controllers/bar_events_controller.rb
#################################################################################
# We only use POST and DELETE for this controller.  There is currently no need
# for us to create, update, or show a bar event via the HTML forms.
#
# Therefore, any non POST or DELETE will be redirected back to the home page.
#################################################################################
class BarEventsController < ApplicationController
  # GET /bar_events
  # GET /bar_events.json
  def index
    # We've got a good mobile user.  Fetch their deals/events
    if session[:user_id]
      xml = BarEvent.get_xml_for_favorites(session[:user_id])
      render :text => xml
      return
      
    # Browser-based request, redirect back to home page.
    else
      redirect_to_home
    end
  end

  # GET /bar_events/1
  # GET /bar_events/1.json
  def show
    redirect_to_home
    
    #@bar_event = BarEvent.find(params[:id])

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render :json => @bar_event }
    #end
  end

  # GET /bar_events/new
  # GET /bar_events/new.json
  def new
    redirect_to_home
    
    #@bar_event = BarEvent.new

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render :json => @bar_event }
    #end
  end

  # GET /bar_events/1/edit
  def edit
    redirect_to_home
    
    #@bar_event = BarEvent.find(params[:id])
  end

  # POST /bar_events
  # POST /bar_events.json
  def create
    @bar_event = BarEvent.new
    @bar_event.bar_id = params[:bar_id]
    @bar_event.detail = params[:detail]
    
    #for header in request.env.select {|k,v| k.match("^HTTP.*")}
    #  print header
    #end
    #print "Bar id: " + request.env["HTTP_BAR_ID"] + "\n"
    #print "Session id: " + request.env["HTTP_SESSION_ID"] + "\n"
    #print "Bar name: " + request.env["HTTP_BAR_NAME"] + "\n"
    #print "CSRF token: " + request.env["HTTP_X_CSRF_TOKEN"] + "\n"
    
    # Get data and save to the bar_event object
    #print params.to_s

    respond_to do |format|
      if @bar_event.save
        #format.html { redirect_to @bar_event, :notice => 'Bar event was successfully created.' }
        format.html { render :text => @bar_event.id }
        format.json { render :json => @bar_event, :status => :created, :location => @bar_event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bar_event.errors, :status => :unprocessable_entity }
      end
	end
  end

  # PUT /bar_events/1
  # PUT /bar_events/1.json
  def update
    redirect_to_home
    
    #@bar_event = BarEvent.find(params[:id])

    #respond_to do |format|
    #  if @bar_event.update_attributes(params[:bar_event])
    #    format.html { redirect_to @bar_event, :notice => 'Bar event was successfully updated.' }
    #    format.json { head :no_content }
    #  else
    #    format.html { render :action => "edit" }
    #    format.json { render :json => @bar_event.errors, :status => :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /bar_events/1
  # DELETE /bar_events/1.json
  def destroy
    @bar_event = BarEvent.find(params[:id])
    @bar_event.destroy

    respond_to do |format|
      #format.html { redirect_to bar_events_url }
      format.html { head :no_content }
      format.json { head :no_content }
    end
  end
end

app/helpers/bar_events_helper.rb
module BarEventsHelper
end

app/views/bar_events/_form.html.erb
<%= form_for(@bar_event) do |f| %>
  <% if @bar_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar_event.errors.count, "error") %> prohibited this bar_event from being saved:</h2>

      <ul>
      <% @bar_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bar_id %><br />
    <%= f.number_field :bar_id %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bar_events/edit.html.erb
<h1>Editing bar_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar_event %> |
<%= link_to 'Back', bar_events_path %>

app/views/bar_events/index.html.erb
<h1>Listing bar_events</h1>

<table>
  <tr>
    <th>Bar</th>
    <th>Detail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bar_events.each do |bar_event| %>
  <tr>
    <td><%= bar_event.bar_id %></td>
    <td><%= bar_event.detail %></td>
    <td><%= link_to 'Show', bar_event %></td>
    <td><%= link_to 'Edit', edit_bar_event_path(bar_event) %></td>
    <td><%= link_to 'Destroy', bar_event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bar event', new_bar_event_path %>

app/views/bar_events/new.html.erb
<h1>New bar_event</h1>

<%= render 'form' %>

<%= link_to 'Back', bar_events_path %>

app/views/bar_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bar:</b>
  <%= @bar_event.bar_id %>
</p>

<p>
  <b>Detail:</b>
  <%= @bar_event.detail %>
</p>


<%= link_to 'Edit', edit_bar_event_path(@bar_event) %> |
<%= link_to 'Back', bar_events_path %>